baseURL = 'http://luvbum.github.io/writingstuff/'
languageCode = 'en-us'
title = 'Writingstuff'
theme="contrast-hugo"

author = "Patrik Lövbom"

[params]
  minimal = false
  excerpts = false
  description = "my blog"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
